# -*- coding: utf-8 -*-
"""keylogger.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19fN6obXj8pkiYXfCwagCfG6nTVNbz4TU

**Key Logger Demonstration [Arpit Raj Katiyar]**
"""

import tkinter as tk
from datetime import datetime

class KeyloggerDemo:
    def __init__(self, root):
        self.root = root
        self.root.title("Educational Keylogger Demo")
        self.root.geometry("520x420")
        self.root.resizable(False, False)

        self.logging = False
        self.log_data = ""

        title = tk.Label(
            root,
            text="Keylogger Demonstration (Educational Only)",
            font=("Arial", 14, "bold")
        )
        title.pack(pady=10)

        info = tk.Label(
            root,
            text="Type inside the box below.\nOnly keys typed here will be logged.",
            font=("Arial", 10)
        )
        info.pack()

        self.text_box = tk.Text(root, height=8, width=55)
        self.text_box.pack(pady=10)
        self.text_box.bind("<Key>", self.capture_key)

        btn_frame = tk.Frame(root)
        btn_frame.pack(pady=5)

        self.start_btn = tk.Button(
            btn_frame, text="Start Logging",
            command=self.start_logging,
            bg="green", fg="white", width=15
        )
        self.start_btn.grid(row=0, column=0, padx=5)

        self.stop_btn = tk.Button(
            btn_frame, text="Stop Logging",
            command=self.stop_logging,
            bg="red", fg="white", width=15
        )
        self.stop_btn.grid(row=0, column=1, padx=5)

        self.save_btn = tk.Button(
            root, text="Save Log",
            command=self.save_log,
            width=20
        )
        self.save_btn.pack(pady=5)

        self.status = tk.Label(
            root, text="Status: Not Logging",
            fg="blue", font=("Arial", 10, "bold")
        )
        self.status.pack(pady=10)

        footer = tk.Label(
            root,
            text="⚠ Educational Purpose Only | No Background Tracking",
            font=("Arial", 9)
        )
        footer.pack(side="bottom", pady=5)

    def start_logging(self):
        self.logging = True
        self.status.config(text="Status: Logging Started", fg="green")

    def stop_logging(self):
        self.logging = False
        self.status.config(text="Status: Logging Stopped", fg="red")

    def capture_key(self, event):
        if self.logging:
            self.log_data += event.keysym + " "

    def save_log(self):
        if self.log_data.strip() == "":
            self.status.config(text="No data to save", fg="orange")
            return

        filename = f"keylog_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
        with open(filename, "w") as file:
            file.write(self.log_data)

        self.status.config(
            text=f"Log saved as {filename}",
            fg="purple"
        )

if __name__ == "__main__":
    root = tk.Tk()
    app = KeyloggerDemo(root)
    root.mainloop()